spring:
  application:
    name: execution
  datasource:
    url: jdbc:postgresql://localhost:5432/${spring.application.name}db

  cloud:
    function:
      definition: commandResponseChannel;executionServiceCommandChannel;executionEventSubscriber;
    stream:
      bindings:
        execution-command-channel:
          destination: ${spring.application.name}-command-channel
        executionServiceCommandChannel-in-0:
          destination: ${spring.application.name}-command-channel
          group: ${spring.application.name}-service-group
        commandResponseChannel-in-0:
          destination: ${spring.application.name}-command-responses
          group: ${spring.application.name}-response-group
        executionEventSubscriber-in-0:
          destination: event-channel
          group: ${spring.application.name}-service-group

server:
  port: 8083
grpc:
  server:
    port: 9093

routes:
  - id: ${spring.application.name}-service-users
    uri: lb://${spring.application.name}${gateway.service-suffix}
    predicates:
      - Path=/users/*/executions
    order: 1

  - id: ${spring.application.name}-service-create
    uri: lb://${spring.application.name}${gateway.service-suffix}
    predicates:
      - Path=/executions/create
    order: 8

  - id: ${spring.application.name}-service
    uri: lb://${spring.application.name}${gateway.service-suffix}
    predicates:
      - Path=/executions/**
    order: 10
