-- H2 2.2.224; 
SET DB_CLOSE_DELAY -1;         
;              
CREATE USER IF NOT EXISTS "SA" SALT '8fadb56619b67c49' HASH 'ce79d351b9298d9cc956ed7c8fd0be1669435870dae05360eba20160fa31347c' ADMIN;          
CREATE SEQUENCE "PUBLIC"."AGGREGATE_ID_GENERATOR_SEQ" START WITH 1 RESTART WITH 101 INCREMENT BY 50;           
CREATE SEQUENCE "PUBLIC"."AGGREGATE_SEQ" START WITH 1 RESTART WITH 101 INCREMENT BY 50;        
CREATE SEQUENCE "PUBLIC"."ANSWERED_QUIZ_SEQ" START WITH 1 INCREMENT BY 50;     
CREATE SEQUENCE "PUBLIC"."ANSWER_COURSE_EXECUTION_SEQ" START WITH 1 INCREMENT BY 50;           
CREATE SEQUENCE "PUBLIC"."ANSWER_STUDENT_SEQ" START WITH 1 INCREMENT BY 50;    
CREATE SEQUENCE "PUBLIC"."COURSE_EXECUTION_COURSE_SEQ" START WITH 1 RESTART WITH 101 INCREMENT BY 50;          
CREATE SEQUENCE "PUBLIC"."COURSE_EXECUTION_STUDENT_SEQ" START WITH 1 RESTART WITH 101 INCREMENT BY 50;         
CREATE SEQUENCE "PUBLIC"."EVENT_SEQ" START WITH 1 RESTART WITH 51 INCREMENT BY 50;             
CREATE SEQUENCE "PUBLIC"."OPTION_SEQ" START WITH 1 RESTART WITH 101 INCREMENT BY 50;           
CREATE SEQUENCE "PUBLIC"."QUESTION_ANSWER_SEQ" START WITH 1 INCREMENT BY 50;   
CREATE SEQUENCE "PUBLIC"."QUESTION_COURSE_SEQ" START WITH 1 RESTART WITH 101 INCREMENT BY 50;  
CREATE SEQUENCE "PUBLIC"."QUESTION_TOPIC_SEQ" START WITH 1 RESTART WITH 101 INCREMENT BY 50;   
CREATE SEQUENCE "PUBLIC"."QUIZ_COURSE_EXECUTION_SEQ" START WITH 1 RESTART WITH 51 INCREMENT BY 50;             
CREATE SEQUENCE "PUBLIC"."QUIZ_QUESTION_SEQ" START WITH 1 RESTART WITH 101 INCREMENT BY 50;    
CREATE SEQUENCE "PUBLIC"."TOPIC_COURSE_SEQ" START WITH 1 RESTART WITH 101 INCREMENT BY 50;     
CREATE SEQUENCE "PUBLIC"."TOURNAMENT_COURSE_EXECUTION_SEQ" START WITH 1 RESTART WITH 101 INCREMENT BY 50;      
CREATE SEQUENCE "PUBLIC"."TOURNAMENT_CREATOR_SEQ" START WITH 1 RESTART WITH 101 INCREMENT BY 50;               
CREATE SEQUENCE "PUBLIC"."TOURNAMENT_PARTICIPANT_QUIZ_ANSWER_SEQ" START WITH 1 RESTART WITH 51 INCREMENT BY 50;
CREATE SEQUENCE "PUBLIC"."TOURNAMENT_PARTICIPANT_SEQ" START WITH 1 RESTART WITH 51 INCREMENT BY 50;            
CREATE SEQUENCE "PUBLIC"."TOURNAMENT_QUIZ_SEQ" START WITH 1 RESTART WITH 101 INCREMENT BY 50;  
CREATE SEQUENCE "PUBLIC"."TOURNAMENT_TOPIC_SEQ" START WITH 1 RESTART WITH 101 INCREMENT BY 50; 
CREATE SEQUENCE "PUBLIC"."VERSION_SEQ" START WITH 1 RESTART WITH 51 INCREMENT BY 50;           
CREATE MEMORY TABLE "PUBLIC"."AGGREGATE_ID_GENERATOR"(
    "ID" INTEGER NOT NULL
);            
ALTER TABLE "PUBLIC"."AGGREGATE_ID_GENERATOR" ADD CONSTRAINT "PUBLIC"."CONSTRAINT_6" PRIMARY KEY("ID");        
-- 12 +/- SELECT COUNT(*) FROM PUBLIC.AGGREGATE_ID_GENERATOR;  
CREATE MEMORY TABLE "PUBLIC"."ANSWER_COURSE_EXECUTION"(
    "COURSE_EXECUTION_AGGREGATE_ID" INTEGER,
    "COURSE_EXECUTION_VERSION" INTEGER,
    "QUIZ_ANSWER_ID" INTEGER,
    "ID" BIGINT NOT NULL
);         
ALTER TABLE "PUBLIC"."ANSWER_COURSE_EXECUTION" ADD CONSTRAINT "PUBLIC"."CONSTRAINT_CA" PRIMARY KEY("ID");      
-- 0 +/- SELECT COUNT(*) FROM PUBLIC.ANSWER_COURSE_EXECUTION;  
CREATE MEMORY TABLE "PUBLIC"."ANSWERED_QUIZ"(
    "QUIZ_AGGREGATE_ID" INTEGER,
    "QUIZ_ANSWER_ID" INTEGER,
    "QUIZ_VERSION" INTEGER,
    "ID" BIGINT NOT NULL
);           
ALTER TABLE "PUBLIC"."ANSWERED_QUIZ" ADD CONSTRAINT "PUBLIC"."CONSTRAINT_2A" PRIMARY KEY("ID");
-- 0 +/- SELECT COUNT(*) FROM PUBLIC.ANSWERED_QUIZ;            
CREATE MEMORY TABLE "PUBLIC"."ANSWERED_QUIZ_QUIZ_QUESTIONS_AGGREGATE_IDS"(
    "QUIZ_QUESTIONS_AGGREGATE_IDS" INTEGER,
    "ANSWERED_QUIZ_ID" BIGINT NOT NULL
);               
-- 0 +/- SELECT COUNT(*) FROM PUBLIC.ANSWERED_QUIZ_QUIZ_QUESTIONS_AGGREGATE_IDS;               
CREATE MEMORY TABLE "PUBLIC"."ANSWER_STUDENT"(
    "QUIZ_ANSWER_ID" INTEGER,
    "STUDENT_AGGREGATE_ID" INTEGER,
    "STUDENT_STATE" TINYINT,
    "ID" BIGINT NOT NULL,
    "NAME" CHARACTER VARYING(255)
);   
ALTER TABLE "PUBLIC"."ANSWER_STUDENT" ADD CONSTRAINT "PUBLIC"."CONSTRAINT_BA9" PRIMARY KEY("ID");              
-- 0 +/- SELECT COUNT(*) FROM PUBLIC.ANSWER_STUDENT;           
CREATE MEMORY TABLE "PUBLIC"."CAUSAL_COURSE"(
    "AGGREGATE_ID" INTEGER,
    "ID" INTEGER NOT NULL,
    "PREV_ID" INTEGER,
    "VERSION" INTEGER,
    "CREATION_TS" TIMESTAMP(6),
    "AGGREGATE_TYPE" CHARACTER VARYING(255),
    "NAME" CHARACTER VARYING(255),
    "STATE" ENUM('ACTIVE', 'DELETED', 'INACTIVE'),
    "TYPE" ENUM('EXTERNAL', 'TECNICO')
);
ALTER TABLE "PUBLIC"."CAUSAL_COURSE" ADD CONSTRAINT "PUBLIC"."CONSTRAINT_9" PRIMARY KEY("ID"); 
-- 0 +/- SELECT COUNT(*) FROM PUBLIC.CAUSAL_COURSE;            
CREATE MEMORY TABLE "PUBLIC"."CAUSAL_COURSE_EXECUTION"(
    "AGGREGATE_ID" INTEGER,
    "ID" INTEGER NOT NULL,
    "PREV_ID" INTEGER,
    "VERSION" INTEGER,
    "CREATION_TS" TIMESTAMP(6),
    "END_DATE" TIMESTAMP(6),
    "ACADEMIC_TERM" CHARACTER VARYING(255),
    "ACRONYM" CHARACTER VARYING(255),
    "AGGREGATE_TYPE" CHARACTER VARYING(255),
    "STATE" ENUM('ACTIVE', 'DELETED', 'INACTIVE')
);  
ALTER TABLE "PUBLIC"."CAUSAL_COURSE_EXECUTION" ADD CONSTRAINT "PUBLIC"."CONSTRAINT_3" PRIMARY KEY("ID");       
-- 0 +/- SELECT COUNT(*) FROM PUBLIC.CAUSAL_COURSE_EXECUTION;  
CREATE MEMORY TABLE "PUBLIC"."CAUSAL_QUESTION"(
    "AGGREGATE_ID" INTEGER,
    "ID" INTEGER NOT NULL,
    "PREV_ID" INTEGER,
    "VERSION" INTEGER,
    "CREATION_DATE" TIMESTAMP(6),
    "CREATION_TS" TIMESTAMP(6),
    "AGGREGATE_TYPE" CHARACTER VARYING(255),
    "CONTENT" CHARACTER VARYING(255),
    "TITLE" CHARACTER VARYING(255),
    "STATE" ENUM('ACTIVE', 'DELETED', 'INACTIVE')
);             
ALTER TABLE "PUBLIC"."CAUSAL_QUESTION" ADD CONSTRAINT "PUBLIC"."CONSTRAINT_D" PRIMARY KEY("ID");               
-- 0 +/- SELECT COUNT(*) FROM PUBLIC.CAUSAL_QUESTION;          
CREATE MEMORY TABLE "PUBLIC"."CAUSAL_QUIZ"(
    "AGGREGATE_ID" INTEGER,
    "ID" INTEGER NOT NULL,
    "PREV_ID" INTEGER,
    "VERSION" INTEGER,
    "AVAILABLE_DATE" TIMESTAMP(6),
    "CONCLUSION_DATE" TIMESTAMP(6),
    "CREATION_DATE" TIMESTAMP(6),
    "CREATION_TS" TIMESTAMP(6),
    "RESULTS_DATE" TIMESTAMP(6),
    "AGGREGATE_TYPE" CHARACTER VARYING(255),
    "TITLE" CHARACTER VARYING(255),
    "QUIZ_TYPE" ENUM('EXAM', 'EXTERNAL_QUIZ', 'GENERATED', 'IN_CLASS', 'PROPOSED', 'TEST'),
    "STATE" ENUM('ACTIVE', 'DELETED', 'INACTIVE')
);   
ALTER TABLE "PUBLIC"."CAUSAL_QUIZ" ADD CONSTRAINT "PUBLIC"."CONSTRAINT_DC" PRIMARY KEY("ID");  
-- 0 +/- SELECT COUNT(*) FROM PUBLIC.CAUSAL_QUIZ;              
CREATE MEMORY TABLE "PUBLIC"."CAUSAL_QUIZ_ANSWER"(
    "AGGREGATE_ID" INTEGER,
    "COMPLETED" BOOLEAN NOT NULL,
    "ID" INTEGER NOT NULL,
    "PREV_ID" INTEGER,
    "VERSION" INTEGER,
    "ANSWER_DATE" TIMESTAMP(6),
    "CREATION_DATE" TIMESTAMP(6),
    "CREATION_TS" TIMESTAMP(6),
    "AGGREGATE_TYPE" CHARACTER VARYING(255),
    "STATE" ENUM('ACTIVE', 'DELETED', 'INACTIVE')
);  
ALTER TABLE "PUBLIC"."CAUSAL_QUIZ_ANSWER" ADD CONSTRAINT "PUBLIC"."CONSTRAINT_1" PRIMARY KEY("ID");            
-- 0 +/- SELECT COUNT(*) FROM PUBLIC.CAUSAL_QUIZ_ANSWER;       
CREATE MEMORY TABLE "PUBLIC"."CAUSAL_TOPIC"(
    "AGGREGATE_ID" INTEGER,
    "ID" INTEGER NOT NULL,
    "PREV_ID" INTEGER,
    "VERSION" INTEGER,
    "CREATION_TS" TIMESTAMP(6),
    "AGGREGATE_TYPE" CHARACTER VARYING(255),
    "NAME" CHARACTER VARYING(255),
    "STATE" ENUM('ACTIVE', 'DELETED', 'INACTIVE')
);         
ALTER TABLE "PUBLIC"."CAUSAL_TOPIC" ADD CONSTRAINT "PUBLIC"."CONSTRAINT_BB" PRIMARY KEY("ID"); 
-- 0 +/- SELECT COUNT(*) FROM PUBLIC.CAUSAL_TOPIC;             
CREATE MEMORY TABLE "PUBLIC"."CAUSAL_TOURNAMENT"(
    "AGGREGATE_ID" INTEGER,
    "CANCELLED" BOOLEAN NOT NULL,
    "ID" INTEGER NOT NULL,
    "NUMBER_OF_QUESTIONS" INTEGER,
    "PREV_ID" INTEGER,
    "VERSION" INTEGER,
    "CREATION_TS" TIMESTAMP(6),
    "END_TIME" TIMESTAMP(6),
    "START_TIME" TIMESTAMP(6),
    "AGGREGATE_TYPE" CHARACTER VARYING(255),
    "STATE" ENUM('ACTIVE', 'DELETED', 'INACTIVE')
);      
ALTER TABLE "PUBLIC"."CAUSAL_TOURNAMENT" ADD CONSTRAINT "PUBLIC"."CONSTRAINT_6D" PRIMARY KEY("ID");            
-- 0 +/- SELECT COUNT(*) FROM PUBLIC.CAUSAL_TOURNAMENT;        
CREATE MEMORY TABLE "PUBLIC"."CAUSAL_USER"(
    "ACTIVE" BOOLEAN DEFAULT FALSE,
    "AGGREGATE_ID" INTEGER,
    "ID" INTEGER NOT NULL,
    "PREV_ID" INTEGER,
    "VERSION" INTEGER,
    "CREATION_TS" TIMESTAMP(6),
    "AGGREGATE_TYPE" CHARACTER VARYING(255),
    "NAME" CHARACTER VARYING(255),
    "USERNAME" CHARACTER VARYING(255),
    "ROLE" ENUM('ADMIN', 'STUDENT', 'TEACHER'),
    "STATE" ENUM('ACTIVE', 'DELETED', 'INACTIVE')
);               
ALTER TABLE "PUBLIC"."CAUSAL_USER" ADD CONSTRAINT "PUBLIC"."CONSTRAINT_DCC" PRIMARY KEY("ID"); 
-- 0 +/- SELECT COUNT(*) FROM PUBLIC.CAUSAL_USER;              
CREATE MEMORY TABLE "PUBLIC"."COURSE_EXECUTION_COURSE"(
    "COURSE_AGGREGATE_ID" INTEGER,
    "COURSE_EXECUTION_ID" INTEGER,
    "COURSE_VERSION" INTEGER,
    "ID" BIGINT NOT NULL,
    "NAME" CHARACTER VARYING(255),
    "TYPE" ENUM('EXTERNAL', 'TECNICO')
);             
ALTER TABLE "PUBLIC"."COURSE_EXECUTION_COURSE" ADD CONSTRAINT "PUBLIC"."CONSTRAINT_76" PRIMARY KEY("ID");      
-- 4 +/- SELECT COUNT(*) FROM PUBLIC.COURSE_EXECUTION_COURSE;  
CREATE MEMORY TABLE "PUBLIC"."COURSE_EXECUTION_STUDENT"(
    "ACTIVE" BOOLEAN NOT NULL,
    "COURSE_EXECUTION_ID" INTEGER,
    "STATE" TINYINT,
    "USER_AGGREGATE_ID" INTEGER,
    "USER_VERSION" INTEGER,
    "ID" BIGINT NOT NULL,
    "NAME" CHARACTER VARYING(255),
    "USERNAME" CHARACTER VARYING(255)
);             
ALTER TABLE "PUBLIC"."COURSE_EXECUTION_STUDENT" ADD CONSTRAINT "PUBLIC"."CONSTRAINT_A8" PRIMARY KEY("ID");     
-- 5 +/- SELECT COUNT(*) FROM PUBLIC.COURSE_EXECUTION_STUDENT; 
CREATE MEMORY TABLE "PUBLIC"."EVENT"(
    "CORRECT" BOOLEAN,
    "ID" INTEGER NOT NULL,
    "PUBLISHER_AGGREGATE_ID" INTEGER,
    "PUBLISHER_AGGREGATE_VERSION" INTEGER,
    "QUESTION_AGGREGATE_ID" INTEGER,
    "QUIZ_AGGREGATE_ID" INTEGER,
    "STUDENT_AGGREGATE_ID" INTEGER,
    "TIMESTAMP" TIMESTAMP(6),
    "DTYPE" CHARACTER VARYING(31) NOT NULL,
    "CONTENT" CHARACTER VARYING(255),
    "NAME" CHARACTER VARYING(255),
    "TITLE" CHARACTER VARYING(255),
    "TOPIC_NAME" CHARACTER VARYING(255),
    "UPDATED_NAME" CHARACTER VARYING(255),
    "USERNAME" CHARACTER VARYING(255)
);         
ALTER TABLE "PUBLIC"."EVENT" ADD CONSTRAINT "PUBLIC"."CONSTRAINT_3F" PRIMARY KEY("ID");        
-- 1 +/- SELECT COUNT(*) FROM PUBLIC.EVENT;    
CREATE MEMORY TABLE "PUBLIC"."OPTION"(
    "CORRECT" BOOLEAN NOT NULL,
    "OPTION_KEY" INTEGER,
    "QUESTION_ID" INTEGER,
    "SEQUENCE" INTEGER,
    "ID" BIGINT NOT NULL,
    "CONTENT" CHARACTER VARYING(255)
);          
ALTER TABLE "PUBLIC"."OPTION" ADD CONSTRAINT "PUBLIC"."CONSTRAINT_8" PRIMARY KEY("ID");        
-- 6 +/- SELECT COUNT(*) FROM PUBLIC.OPTION;   
CREATE MEMORY TABLE "PUBLIC"."QUESTION_ANSWER"(
    "CORRECT" BOOLEAN NOT NULL,
    "OPTION_KEY" INTEGER,
    "OPTION_SEQUENCE_CHOICE" INTEGER,
    "QUESTION_AGGREGATE_ID" INTEGER,
    "QUESTION_VERSION" INTEGER,
    "QUIZ_ANSWER_ID" INTEGER,
    "STATE" TINYINT,
    "TIME_TAKEN" INTEGER,
    "ID" BIGINT NOT NULL
);  
ALTER TABLE "PUBLIC"."QUESTION_ANSWER" ADD CONSTRAINT "PUBLIC"."CONSTRAINT_357" PRIMARY KEY("ID");             
-- 0 +/- SELECT COUNT(*) FROM PUBLIC.QUESTION_ANSWER;          
CREATE MEMORY TABLE "PUBLIC"."QUESTION_COURSE"(
    "COURSE_AGGREGATE_ID" INTEGER,
    "COURSE_VERSION" INTEGER,
    "QUESTION_ID" INTEGER,
    "ID" BIGINT NOT NULL,
    "COURSE_NAME" CHARACTER VARYING(255)
);              
ALTER TABLE "PUBLIC"."QUESTION_COURSE" ADD CONSTRAINT "PUBLIC"."CONSTRAINT_38F" PRIMARY KEY("ID");             
-- 3 +/- SELECT COUNT(*) FROM PUBLIC.QUESTION_COURSE;          
CREATE MEMORY TABLE "PUBLIC"."QUESTION_TOPIC"(
    "QUESTION_ID" INTEGER,
    "STATE" TINYINT,
    "TOPIC_AGGREGATE_ID" INTEGER,
    "TOPIC_VERSION" INTEGER,
    "ID" BIGINT NOT NULL,
    "TOPIC_NAME" CHARACTER VARYING(255)
);             
ALTER TABLE "PUBLIC"."QUESTION_TOPIC" ADD CONSTRAINT "PUBLIC"."CONSTRAINT_44" PRIMARY KEY("ID");               
-- 3 +/- SELECT COUNT(*) FROM PUBLIC.QUESTION_TOPIC;           
CREATE MEMORY TABLE "PUBLIC"."QUIZ_COURSE_EXECUTION"(
    "COURSE_EXECUTION_AGGREGATE_ID" INTEGER,
    "COURSE_EXECUTION_VERSION" INTEGER,
    "QUIZ_ID" INTEGER,
    "ID" BIGINT NOT NULL
);  
ALTER TABLE "PUBLIC"."QUIZ_COURSE_EXECUTION" ADD CONSTRAINT "PUBLIC"."CONSTRAINT_6A1" PRIMARY KEY("ID");       
-- 1 +/- SELECT COUNT(*) FROM PUBLIC.QUIZ_COURSE_EXECUTION;    
CREATE MEMORY TABLE "PUBLIC"."QUIZ_QUESTION"(
    "QUESTION_AGGREGATE_ID" INTEGER,
    "QUESTION_VERSION" INTEGER,
    "QUIZ_ID" INTEGER,
    "SEQUENCE" INTEGER,
    "STATE" TINYINT,
    "ID" BIGINT NOT NULL,
    "CONTENT" CHARACTER VARYING(255),
    "TITLE" CHARACTER VARYING(255)
);   
ALTER TABLE "PUBLIC"."QUIZ_QUESTION" ADD CONSTRAINT "PUBLIC"."CONSTRAINT_4B0" PRIMARY KEY("ID");               
-- 2 +/- SELECT COUNT(*) FROM PUBLIC.QUIZ_QUESTION;            
CREATE MEMORY TABLE "PUBLIC"."SAGA_COURSE"(
    "AGGREGATE_ID" INTEGER,
    "ID" INTEGER NOT NULL,
    "PREV_ID" INTEGER,
    "VERSION" INTEGER,
    "CREATION_TS" TIMESTAMP(6),
    "AGGREGATE_TYPE" CHARACTER VARYING(255),
    "NAME" CHARACTER VARYING(255),
    "SAGA_STATE" CHARACTER VARYING(255),
    "STATE" ENUM('ACTIVE', 'DELETED', 'INACTIVE'),
    "TYPE" ENUM('EXTERNAL', 'TECNICO')
);         
ALTER TABLE "PUBLIC"."SAGA_COURSE" ADD CONSTRAINT "PUBLIC"."CONSTRAINT_E" PRIMARY KEY("ID");   
-- 1 +/- SELECT COUNT(*) FROM PUBLIC.SAGA_COURSE;              
CREATE MEMORY TABLE "PUBLIC"."SAGA_COURSE_EXECUTION"(
    "AGGREGATE_ID" INTEGER,
    "ID" INTEGER NOT NULL,
    "PREV_ID" INTEGER,
    "VERSION" INTEGER,
    "CREATION_TS" TIMESTAMP(6),
    "END_DATE" TIMESTAMP(6),
    "ACADEMIC_TERM" CHARACTER VARYING(255),
    "ACRONYM" CHARACTER VARYING(255),
    "AGGREGATE_TYPE" CHARACTER VARYING(255),
    "SAGA_STATE" CHARACTER VARYING(255),
    "STATE" ENUM('ACTIVE', 'DELETED', 'INACTIVE')
);           
ALTER TABLE "PUBLIC"."SAGA_COURSE_EXECUTION" ADD CONSTRAINT "PUBLIC"."CONSTRAINT_9D" PRIMARY KEY("ID");        
-- 4 +/- SELECT COUNT(*) FROM PUBLIC.SAGA_COURSE_EXECUTION;    
CREATE MEMORY TABLE "PUBLIC"."SAGA_QUESTION"(
    "AGGREGATE_ID" INTEGER,
    "ID" INTEGER NOT NULL,
    "PREV_ID" INTEGER,
    "VERSION" INTEGER,
    "CREATION_DATE" TIMESTAMP(6),
    "CREATION_TS" TIMESTAMP(6),
    "AGGREGATE_TYPE" CHARACTER VARYING(255),
    "CONTENT" CHARACTER VARYING(255),
    "SAGA_STATE" CHARACTER VARYING(255),
    "TITLE" CHARACTER VARYING(255),
    "STATE" ENUM('ACTIVE', 'DELETED', 'INACTIVE')
);      
ALTER TABLE "PUBLIC"."SAGA_QUESTION" ADD CONSTRAINT "PUBLIC"."CONSTRAINT_89" PRIMARY KEY("ID");
-- 3 +/- SELECT COUNT(*) FROM PUBLIC.SAGA_QUESTION;            
CREATE MEMORY TABLE "PUBLIC"."SAGA_QUIZ"(
    "AGGREGATE_ID" INTEGER,
    "ID" INTEGER NOT NULL,
    "PREV_ID" INTEGER,
    "VERSION" INTEGER,
    "AVAILABLE_DATE" TIMESTAMP(6),
    "CONCLUSION_DATE" TIMESTAMP(6),
    "CREATION_DATE" TIMESTAMP(6),
    "CREATION_TS" TIMESTAMP(6),
    "RESULTS_DATE" TIMESTAMP(6),
    "AGGREGATE_TYPE" CHARACTER VARYING(255),
    "SAGA_STATE" CHARACTER VARYING(255),
    "TITLE" CHARACTER VARYING(255),
    "QUIZ_TYPE" ENUM('EXAM', 'EXTERNAL_QUIZ', 'GENERATED', 'IN_CLASS', 'PROPOSED', 'TEST'),
    "STATE" ENUM('ACTIVE', 'DELETED', 'INACTIVE')
);            
ALTER TABLE "PUBLIC"."SAGA_QUIZ" ADD CONSTRAINT "PUBLIC"."CONSTRAINT_92" PRIMARY KEY("ID");    
-- 1 +/- SELECT COUNT(*) FROM PUBLIC.SAGA_QUIZ;
CREATE MEMORY TABLE "PUBLIC"."SAGA_QUIZ_ANSWER"(
    "AGGREGATE_ID" INTEGER,
    "COMPLETED" BOOLEAN NOT NULL,
    "ID" INTEGER NOT NULL,
    "PREV_ID" INTEGER,
    "VERSION" INTEGER,
    "ANSWER_DATE" TIMESTAMP(6),
    "CREATION_DATE" TIMESTAMP(6),
    "CREATION_TS" TIMESTAMP(6),
    "AGGREGATE_TYPE" CHARACTER VARYING(255),
    "SAGA_STATE" CHARACTER VARYING(255),
    "STATE" ENUM('ACTIVE', 'DELETED', 'INACTIVE')
);           
ALTER TABLE "PUBLIC"."SAGA_QUIZ_ANSWER" ADD CONSTRAINT "PUBLIC"."CONSTRAINT_1B" PRIMARY KEY("ID");             
-- 0 +/- SELECT COUNT(*) FROM PUBLIC.SAGA_QUIZ_ANSWER;         
CREATE MEMORY TABLE "PUBLIC"."SAGA_TOPIC"(
    "AGGREGATE_ID" INTEGER,
    "ID" INTEGER NOT NULL,
    "PREV_ID" INTEGER,
    "VERSION" INTEGER,
    "CREATION_TS" TIMESTAMP(6),
    "AGGREGATE_TYPE" CHARACTER VARYING(255),
    "NAME" CHARACTER VARYING(255),
    "SAGA_STATE" CHARACTER VARYING(255),
    "STATE" ENUM('ACTIVE', 'DELETED', 'INACTIVE')
);  
ALTER TABLE "PUBLIC"."SAGA_TOPIC" ADD CONSTRAINT "PUBLIC"."CONSTRAINT_BD" PRIMARY KEY("ID");   
-- 3 +/- SELECT COUNT(*) FROM PUBLIC.SAGA_TOPIC;               
CREATE MEMORY TABLE "PUBLIC"."SAGA_TOURNAMENT"(
    "AGGREGATE_ID" INTEGER,
    "CANCELLED" BOOLEAN NOT NULL,
    "ID" INTEGER NOT NULL,
    "NUMBER_OF_QUESTIONS" INTEGER,
    "PREV_ID" INTEGER,
    "VERSION" INTEGER,
    "CREATION_TS" TIMESTAMP(6),
    "END_TIME" TIMESTAMP(6),
    "START_TIME" TIMESTAMP(6),
    "AGGREGATE_TYPE" CHARACTER VARYING(255),
    "SAGA_STATE" CHARACTER VARYING(255),
    "STATE" ENUM('ACTIVE', 'DELETED', 'INACTIVE')
);               
ALTER TABLE "PUBLIC"."SAGA_TOURNAMENT" ADD CONSTRAINT "PUBLIC"."CONSTRAINT_B8" PRIMARY KEY("ID");              
-- 3 +/- SELECT COUNT(*) FROM PUBLIC.SAGA_TOURNAMENT;          
CREATE MEMORY TABLE "PUBLIC"."SAGA_USER"(
    "ACTIVE" BOOLEAN DEFAULT FALSE,
    "AGGREGATE_ID" INTEGER,
    "ID" INTEGER NOT NULL,
    "PREV_ID" INTEGER,
    "VERSION" INTEGER,
    "CREATION_TS" TIMESTAMP(6),
    "AGGREGATE_TYPE" CHARACTER VARYING(255),
    "NAME" CHARACTER VARYING(255),
    "SAGA_STATE" CHARACTER VARYING(255),
    "USERNAME" CHARACTER VARYING(255),
    "ROLE" ENUM('ADMIN', 'STUDENT', 'TEACHER'),
    "STATE" ENUM('ACTIVE', 'DELETED', 'INACTIVE')
);        
ALTER TABLE "PUBLIC"."SAGA_USER" ADD CONSTRAINT "PUBLIC"."CONSTRAINT_928" PRIMARY KEY("ID");   
-- 4 +/- SELECT COUNT(*) FROM PUBLIC.SAGA_USER;
CREATE MEMORY TABLE "PUBLIC"."TOPIC_COURSE"(
    "COURSE_AGGREGATE_ID" INTEGER,
    "COURSE_VERSION" INTEGER,
    "ID" INTEGER NOT NULL,
    "TOPIC_ID" INTEGER
);             
ALTER TABLE "PUBLIC"."TOPIC_COURSE" ADD CONSTRAINT "PUBLIC"."CONSTRAINT_5F" PRIMARY KEY("ID"); 
-- 3 +/- SELECT COUNT(*) FROM PUBLIC.TOPIC_COURSE;             
CREATE MEMORY TABLE "PUBLIC"."TOURNAMENT_COURSE_EXECUTION"(
    "COURSE_EXECUTION_AGGREGATE_ID" INTEGER,
    "COURSE_EXECUTION_COURSE_ID" INTEGER,
    "COURSE_EXECUTION_VERSION" INTEGER,
    "TOURNAMENT_ID" INTEGER,
    "ID" BIGINT NOT NULL,
    "COURSE_EXECUTION_ACRONYM" CHARACTER VARYING(255),
    "COURSE_EXECUTION_STATUS" CHARACTER VARYING(255)
);               
ALTER TABLE "PUBLIC"."TOURNAMENT_COURSE_EXECUTION" ADD CONSTRAINT "PUBLIC"."CONSTRAINT_E6C" PRIMARY KEY("ID"); 
-- 3 +/- SELECT COUNT(*) FROM PUBLIC.TOURNAMENT_COURSE_EXECUTION;              
CREATE MEMORY TABLE "PUBLIC"."TOURNAMENT_CREATOR"(
    "CREATOR_AGGREGATE_ID" INTEGER,
    "CREATOR_STATE" TINYINT,
    "CREATOR_VERSION" INTEGER,
    "TOURNAMENT_ID" INTEGER,
    "ID" BIGINT NOT NULL,
    "CREATOR_NAME" CHARACTER VARYING(255),
    "CREATOR_USERNAME" CHARACTER VARYING(255)
);          
ALTER TABLE "PUBLIC"."TOURNAMENT_CREATOR" ADD CONSTRAINT "PUBLIC"."CONSTRAINT_EE69" PRIMARY KEY("ID");         
-- 3 +/- SELECT COUNT(*) FROM PUBLIC.TOURNAMENT_CREATOR;       
CREATE MEMORY TABLE "PUBLIC"."TOURNAMENT_PARTICIPANT"(
    "PARTICIPANT_AGGREGATE_ID" INTEGER,
    "PARTICIPANT_VERSION" INTEGER,
    "TOURNAMENT_ID" INTEGER,
    "ENROLL_TIME" TIMESTAMP(6),
    "ID" BIGINT NOT NULL,
    "PARTICIPANT_NAME" CHARACTER VARYING(255),
    "PARTICIPANT_USERNAME" CHARACTER VARYING(255),
    "STATE" ENUM('ACTIVE', 'DELETED', 'INACTIVE')
);
ALTER TABLE "PUBLIC"."TOURNAMENT_PARTICIPANT" ADD CONSTRAINT "PUBLIC"."CONSTRAINT_DE" PRIMARY KEY("ID");       
-- 1 +/- SELECT COUNT(*) FROM PUBLIC.TOURNAMENT_PARTICIPANT;   
CREATE MEMORY TABLE "PUBLIC"."TOURNAMENT_PARTICIPANT_QUIZ_ANSWER"(
    "ANSWERED" BOOLEAN NOT NULL,
    "NUMBER_OF_ANSWERED" INTEGER,
    "NUMBER_OF_CORRECT" INTEGER,
    "QUIZ_ANSWER_AGGREGATE_ID" INTEGER,
    "QUIZ_ANSWER_VERSION" INTEGER,
    "ID" BIGINT NOT NULL,
    "TOURNAMENT_PARTICIPANT_ID" BIGINT
);          
ALTER TABLE "PUBLIC"."TOURNAMENT_PARTICIPANT_QUIZ_ANSWER" ADD CONSTRAINT "PUBLIC"."CONSTRAINT_A89B" PRIMARY KEY("ID");         
-- 1 +/- SELECT COUNT(*) FROM PUBLIC.TOURNAMENT_PARTICIPANT_QUIZ_ANSWER;       
CREATE MEMORY TABLE "PUBLIC"."TOURNAMENT_QUIZ"(
    "QUIZ_AGGREGATE_ID" INTEGER,
    "QUIZ_VERSION" INTEGER,
    "TOURNAMENT_ID" INTEGER,
    "ID" BIGINT NOT NULL
);          
ALTER TABLE "PUBLIC"."TOURNAMENT_QUIZ" ADD CONSTRAINT "PUBLIC"."CONSTRAINT_875" PRIMARY KEY("ID");             
-- 3 +/- SELECT COUNT(*) FROM PUBLIC.TOURNAMENT_QUIZ;          
CREATE MEMORY TABLE "PUBLIC"."TOURNAMENT_TOPIC"(
    "TOPIC_AGGREGATE_ID" INTEGER,
    "TOPIC_COURSE_AGGREGATE_ID" INTEGER,
    "TOPIC_VERSION" INTEGER,
    "TOURNAMENT_ID" INTEGER,
    "ID" BIGINT NOT NULL,
    "TOPIC_NAME" CHARACTER VARYING(255),
    "STATE" ENUM('ACTIVE', 'DELETED', 'INACTIVE')
);  
ALTER TABLE "PUBLIC"."TOURNAMENT_TOPIC" ADD CONSTRAINT "PUBLIC"."CONSTRAINT_62" PRIMARY KEY("ID");             
-- 6 +/- SELECT COUNT(*) FROM PUBLIC.TOURNAMENT_TOPIC;         
CREATE MEMORY TABLE "PUBLIC"."VERSION"(
    "ID" INTEGER NOT NULL,
    "NUMBER_OF_DECREMENTS" INTEGER,
    "VERSION_NUMBER" INTEGER
);         
ALTER TABLE "PUBLIC"."VERSION" ADD CONSTRAINT "PUBLIC"."CONSTRAINT_3FC" PRIMARY KEY("ID");     
-- 1 +/- SELECT COUNT(*) FROM PUBLIC.VERSION;  
ALTER TABLE "PUBLIC"."COURSE_EXECUTION_STUDENT" ADD CONSTRAINT "PUBLIC"."CONSTRAINT_A" CHECK("STATE" BETWEEN 0 AND 2) NOCHECK; 
ALTER TABLE "PUBLIC"."QUESTION_TOPIC" ADD CONSTRAINT "PUBLIC"."CONSTRAINT_4" CHECK("STATE" BETWEEN 0 AND 2) NOCHECK;           
ALTER TABLE "PUBLIC"."QUIZ_QUESTION" ADD CONSTRAINT "PUBLIC"."CONSTRAINT_4B" CHECK("STATE" BETWEEN 0 AND 2) NOCHECK;           
ALTER TABLE "PUBLIC"."QUESTION_ANSWER" ADD CONSTRAINT "PUBLIC"."CONSTRAINT_35" CHECK("STATE" BETWEEN 0 AND 2) NOCHECK;         
ALTER TABLE "PUBLIC"."ANSWER_STUDENT" ADD CONSTRAINT "PUBLIC"."CONSTRAINT_BA" CHECK("STUDENT_STATE" BETWEEN 0 AND 2) NOCHECK;  
ALTER TABLE "PUBLIC"."TOURNAMENT_CREATOR" ADD CONSTRAINT "PUBLIC"."CONSTRAINT_EE" CHECK("CREATOR_STATE" BETWEEN 0 AND 2) NOCHECK;              
ALTER TABLE "PUBLIC"."ANSWERED_QUIZ" ADD CONSTRAINT "PUBLIC"."CONSTRAINT_2" UNIQUE("QUIZ_ANSWER_ID");          
ALTER TABLE "PUBLIC"."TOURNAMENT_QUIZ" ADD CONSTRAINT "PUBLIC"."CONSTRAINT_87" UNIQUE("TOURNAMENT_ID");        
ALTER TABLE "PUBLIC"."TOPIC_COURSE" ADD CONSTRAINT "PUBLIC"."CONSTRAINT_5" UNIQUE("TOPIC_ID"); 
ALTER TABLE "PUBLIC"."COURSE_EXECUTION_COURSE" ADD CONSTRAINT "PUBLIC"."CONSTRAINT_7" UNIQUE("COURSE_EXECUTION_ID");           
ALTER TABLE "PUBLIC"."TOURNAMENT_COURSE_EXECUTION" ADD CONSTRAINT "PUBLIC"."CONSTRAINT_E6" UNIQUE("TOURNAMENT_ID");            
ALTER TABLE "PUBLIC"."QUESTION_COURSE" ADD CONSTRAINT "PUBLIC"."CONSTRAINT_38" UNIQUE("QUESTION_ID");          
ALTER TABLE "PUBLIC"."ANSWER_STUDENT" ADD CONSTRAINT "PUBLIC"."CONSTRAINT_B" UNIQUE("QUIZ_ANSWER_ID");         
ALTER TABLE "PUBLIC"."ANSWER_COURSE_EXECUTION" ADD CONSTRAINT "PUBLIC"."CONSTRAINT_C" UNIQUE("QUIZ_ANSWER_ID");
ALTER TABLE "PUBLIC"."QUIZ_COURSE_EXECUTION" ADD CONSTRAINT "PUBLIC"."CONSTRAINT_6A" UNIQUE("QUIZ_ID");        
ALTER TABLE "PUBLIC"."TOURNAMENT_CREATOR" ADD CONSTRAINT "PUBLIC"."CONSTRAINT_EE6" UNIQUE("TOURNAMENT_ID");    
ALTER TABLE "PUBLIC"."TOURNAMENT_PARTICIPANT_QUIZ_ANSWER" ADD CONSTRAINT "PUBLIC"."CONSTRAINT_A89" UNIQUE("TOURNAMENT_PARTICIPANT_ID");        
ALTER TABLE "PUBLIC"."TOURNAMENT_PARTICIPANT_QUIZ_ANSWER" ADD CONSTRAINT "PUBLIC"."FKDK8XEEHQGGIANMHFBRA77588B" FOREIGN KEY("TOURNAMENT_PARTICIPANT_ID") REFERENCES "PUBLIC"."TOURNAMENT_PARTICIPANT"("ID") NOCHECK;           
ALTER TABLE "PUBLIC"."ANSWERED_QUIZ_QUIZ_QUESTIONS_AGGREGATE_IDS" ADD CONSTRAINT "PUBLIC"."FK7HVTLW9P2OY9IUS120VT8FRY8" FOREIGN KEY("ANSWERED_QUIZ_ID") REFERENCES "PUBLIC"."ANSWERED_QUIZ"("ID") NOCHECK;     
