import * as path from 'path';
import { ConfigContext } from './config-types.js';
import { OrchestrationBase } from '../../shared/orchestration-base.js';

export class DockerConfigGenerator extends OrchestrationBase {
  async generateDockerfile(context: ConfigContext): Promise<void> {
    const content = this.getDockerfileTemplate(context.projectName, context.architecture, context.features);
    const filePath = path.join(context.outputDirectory, 'Dockerfile');
    await this.writeFile(filePath, content, 'Dockerfile');
  }

  async generateDockerCompose(context: ConfigContext): Promise<void> {
    const content = this.getDockerComposeTemplate(context.projectName, context.architecture, context.features);
    const filePath = path.join(context.outputDirectory, 'docker-compose.yml');
    await this.writeFile(filePath, content, 'docker-compose.yml');
  }

  private getDockerfileTemplate(projectName: string, architecture: string, features: string[]): string {
    const serviceName = this.getServiceName(projectName);

    return `# Multi-stage Docker build for ${serviceName}
FROM amazoncorretto:17-alpine as builder

# Install Maven
RUN apk add --no-cache maven

# Set working directory
WORKDIR /app

# Copy pom.xml
COPY pom.xml .

# Download dependencies (this layer will be cached if pom.xml doesn't change)
RUN mvn dependency:go-offline -B

# Copy source code
COPY src src

# Build the application
RUN mvn clean package -DskipTests

# Production stage
FROM amazoncorretto:17-alpine

# Install curl for health checks and create non-root user for security
RUN apk add --no-cache curl && \
    addgroup -g 1001 -S appuser && \
    adduser -u 1001 -S appuser -G appuser

# Set working directory
WORKDIR /app

# Copy the built jar from builder stage
COPY --from=builder /app/target/*.jar app.jar

# Change ownership to non-root user
RUN chown -R appuser:appuser /app
USER appuser

# Expose port
EXPOSE ${this.getPort(projectName)}

# Health check
HEALTHCHECK --interval=30s --timeout=3s --start-period=5s --retries=3 \\
    CMD curl -f http://localhost:${this.getPort(projectName)}/actuator/health || exit 1

# JVM optimization for containers
ENV JAVA_OPTS="-XX:+UseContainerSupport -XX:MaxRAMPercentage=75.0 -XX:+UseG1GC -XX:+UseStringDeduplication"

# Run the application
ENTRYPOINT ["sh", "-c", "java \${JAVA_OPTS} -jar app.jar"]

# Labels for better container management
LABEL maintainer="Generated by Nebula DSL"
LABEL service.name="${serviceName}"
LABEL service.version="1.0.0"
LABEL architecture="${architecture}"
${features.length > 0 ? `LABEL features="${features.join(',')}"` : ''}`;
  }

  private getDockerComposeTemplate(projectName: string, architecture: string, features: string[]): string {
    const serviceName = this.getServiceName(projectName);
    const dbName = this.getDatabaseName(projectName);
    const port = this.getPort(projectName);
    const dbConfig = this.getDatabaseConfig();
    const dbType = this.getDatabaseType();
    const jdbcUrl = this.getJdbcUrl(projectName);

    let services = `version: '3.8'

services:
  ${serviceName}:
    build: .
    container_name: ${serviceName}
    ports:
      - "\${APP_PORT:-${port}}:${port}"
    environment:
      - SPRING_PROFILES_ACTIVE=\${SPRING_PROFILES_ACTIVE:-sagas}
      - SPRING_DATASOURCE_URL=${jdbcUrl}
      - SPRING_DATASOURCE_USERNAME=\${${dbType.toUpperCase()}_USER:-${dbConfig.username}}
      - SPRING_DATASOURCE_PASSWORD=\${${dbType.toUpperCase()}_PASSWORD:-${dbConfig.password}}
${dbType !== 'h2' ? `    depends_on:
      ${dbType}:
        condition: service_healthy` : ''}
    networks:
      - ${serviceName}-network
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:${port}/actuator/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

${this.getDatabaseServiceTemplate(serviceName, dbName, dbType, dbConfig)}`;

    if (this.hasFeature(features, 'saga') || this.hasFeature(features, 'events')) {
      services += `

  redis:
    image: redis:7-alpine
    container_name: ${serviceName}-redis
    ports:
      - "\${REDIS_PORT:-6379}:6379"
    volumes:
      - redis_data:/data
    networks:
      - ${serviceName}-network
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 3s
      retries: 3`;
    }

    if (this.hasFeature(features, 'monitoring')) {
      services += `

  prometheus:
    image: prom/prometheus:latest
    container_name: ${serviceName}-prometheus
    ports:
      - "9090:9090"
    volumes:
      - ./monitoring/prometheus.yml:/etc/prometheus/prometheus.yml
      - prometheus_data:/prometheus
    networks:
      - ${serviceName}-network
    restart: unless-stopped

  grafana:
    image: grafana/grafana:latest
    container_name: ${serviceName}-grafana
    ports:
      - "3000:3000"
    volumes:
      - grafana_data:/var/lib/grafana
      - ./monitoring/grafana:/etc/grafana/provisioning
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=\${GRAFANA_PASSWORD:-admin}
    networks:
      - ${serviceName}-network
    restart: unless-stopped`;
    }

    let volumes = `

volumes:
  ${this.getDatabaseVolumeTemplate(dbType)}`;

    if (this.hasFeature(features, 'saga') || this.hasFeature(features, 'events')) {
      volumes += `
  redis_data:
    driver: local`;
    }

    if (this.hasFeature(features, 'monitoring')) {
      volumes += `
  prometheus_data:
    driver: local
  grafana_data:
    driver: local`;
    }

    const networks = `

networks:
  ${serviceName}-network:
    driver: bridge
    name: ${serviceName}-network`;

    return services + volumes + networks;
  }

  protected getServiceName(projectName: string): string {
    return projectName.toLowerCase().replace(/[^a-z0-9]/g, '-');
  }

  protected getPort(projectName: string): number {
    let hash = 0;
    for (let i = 0; i < projectName.length; i++) {
      const char = projectName.charCodeAt(i);
      hash = ((hash << 5) - hash) + char;
      hash = hash & hash;
    }
    return 8080 + (Math.abs(hash) % 1920);
  }

  private getDatabaseServiceTemplate(serviceName: string, dbName: string, dbType: string, dbConfig: any): string {
    switch (dbType) {
      case 'postgresql':
        return `  postgresql:
    image: postgres:15-alpine
    container_name: ${serviceName}-postgresql
    environment:
      - POSTGRES_DB=\${POSTGRES_DB:-${dbName}}
      - POSTGRES_USER=\${POSTGRES_USER:-${dbConfig.username}}
      - POSTGRES_PASSWORD=\${POSTGRES_PASSWORD:-${dbConfig.password}}
    ports:
      - "\${POSTGRES_PORT:-${dbConfig.port}}:5432"
    volumes:
      - postgresql_data:/var/lib/postgresql/data
      - ./init-scripts:/docker-entrypoint-initdb.d
    networks:
      - ${serviceName}-network
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U \${POSTGRES_USER:-${dbConfig.username}} -d \${POSTGRES_DB:-${dbName}}"]
      interval: 10s
      timeout: 5s
      retries: 5`;

      case 'mysql':
        return `  mysql:
    image: mysql:8.0
    container_name: ${serviceName}-mysql
    environment:
      - MYSQL_DATABASE=\${MYSQL_DATABASE:-${dbName}}
      - MYSQL_USER=\${MYSQL_USER:-${dbConfig.username}}
      - MYSQL_PASSWORD=\${MYSQL_PASSWORD:-${dbConfig.password}}
      - MYSQL_ROOT_PASSWORD=\${MYSQL_ROOT_PASSWORD:-rootpassword}
    ports:
      - "\${MYSQL_PORT:-${dbConfig.port}}:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      - ./init-scripts:/docker-entrypoint-initdb.d
    networks:
      - ${serviceName}-network
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u\${MYSQL_USER:-${dbConfig.username}}", "-p\${MYSQL_PASSWORD:-${dbConfig.password}}"]
      interval: 10s
      timeout: 5s
      retries: 5`;

      case 'mongodb':
        return `  mongodb:
    image: mongo:7.0
    container_name: ${serviceName}-mongodb
    environment:
      - MONGO_INITDB_DATABASE=\${MONGO_INITDB_DATABASE:-${dbName}}
      - MONGO_INITDB_ROOT_USERNAME=\${MONGO_INITDB_ROOT_USERNAME:-${dbConfig.username}}
      - MONGO_INITDB_ROOT_PASSWORD=\${MONGO_INITDB_ROOT_PASSWORD:-${dbConfig.password}}
    ports:
      - "\${MONGO_PORT:-${dbConfig.port}}:27017"
    volumes:
      - mongodb_data:/data/db
      - ./init-scripts:/docker-entrypoint-initdb.d
    networks:
      - ${serviceName}-network
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "mongosh", "--eval", "db.adminCommand('ping')"]
      interval: 10s
      timeout: 5s
      retries: 5`;

      case 'h2':
        // H2 doesn't need a separate service as it's embedded
        return '';

      default:
        return this.getDatabaseServiceTemplate(serviceName, dbName, 'postgresql', dbConfig);
    }
  }

  private getDatabaseVolumeTemplate(dbType: string): string {
    switch (dbType) {
      case 'postgresql':
        return `postgresql_data:
    driver: local`;
      case 'mysql':
        return `mysql_data:
    driver: local`;
      case 'mongodb':
        return `mongodb_data:
    driver: local`;
      case 'h2':
        return '';
      default:
        return `postgresql_data:
    driver: local`;
    }
  }
}
