BASELINE_SCENARIOS = [
    {
        "course_id": 1,
        "topic_id": 3,
        "execution_id": 2,
        "owner_id": 7,
        "tournament_id": 9,
        "user_id": 10,
    },
    {
        "course_id": 11,
        "topic_id": 13,
        "execution_id": 12,
        "owner_id": 17,
        "tournament_id": 19,
        "user_id": 20,
    },
    {
        "course_id": 21,
        "topic_id": 23,
        "execution_id": 22,
        "owner_id": 27,
        "tournament_id": 29,
        "user_id": 30,
    },
    {
        "course_id": 31,
        "topic_id": 33,
        "execution_id": 32,
        "owner_id": 37,
        "tournament_id": 39,
        "user_id": 40,
    },
    {
        "course_id": 41,
        "topic_id": 43,
        "execution_id": 42,
        "owner_id": 47,
        "tournament_id": 49,
        "user_id": 50,
    },
    {
        "course_id": 51,
        "topic_id": 53,
        "execution_id": 52,
        "owner_id": 57,
        "tournament_id": 59,
        "user_id": 60,
    },
    {
        "course_id": 61,
        "topic_id": 63,
        "execution_id": 62,
        "owner_id": 67,
        "tournament_id": 69,
        "user_id": 70,
    },
    {
        "course_id": 71,
        "topic_id": 73,
        "execution_id": 72,
        "owner_id": 77,
        "tournament_id": 79,
        "user_id": 80,
    },
    {
        "course_id": 81,
        "topic_id": 83,
        "execution_id": 82,
        "owner_id": 87,
        "tournament_id": 89,
        "user_id": 90,
    },
    {
        "course_id": 91,
        "topic_id": 93,
        "execution_id": 92,
        "owner_id": 97,
        "tournament_id": 99,
        "user_id": 100,
    },
    {
        "course_id": 101,
        "topic_id": 103,
        "execution_id": 102,
        "owner_id": 107,
        "tournament_id": 109,
        "user_id": 110,
    },
    {
        "course_id": 111,
        "topic_id": 113,
        "execution_id": 112,
        "owner_id": 117,
        "tournament_id": 119,
        "user_id": 120,
    },
    {
        "course_id": 121,
        "topic_id": 123,
        "execution_id": 122,
        "owner_id": 127,
        "tournament_id": 129,
        "user_id": 130,
    },
    {
        "course_id": 131,
        "topic_id": 133,
        "execution_id": 132,
        "owner_id": 137,
        "tournament_id": 139,
        "user_id": 140,
    },
    {
        "course_id": 141,
        "topic_id": 143,
        "execution_id": 142,
        "owner_id": 147,
        "tournament_id": 149,
        "user_id": 150,
    },
    {
        "course_id": 151,
        "topic_id": 153,
        "execution_id": 152,
        "owner_id": 157,
        "tournament_id": 159,
        "user_id": 160,
    },
    {
        "course_id": 161,
        "topic_id": 163,
        "execution_id": 162,
        "owner_id": 167,
        "tournament_id": 169,
        "user_id": 170,
    },
    {
        "course_id": 171,
        "topic_id": 173,
        "execution_id": 172,
        "owner_id": 177,
        "tournament_id": 179,
        "user_id": 180,
    },
    {
        "course_id": 181,
        "topic_id": 183,
        "execution_id": 182,
        "owner_id": 187,
        "tournament_id": 189,
        "user_id": 190,
    },
    {
        "course_id": 191,
        "topic_id": 193,
        "execution_id": 192,
        "owner_id": 197,
        "tournament_id": 199,
        "user_id": 200,
    },
    {
        "course_id": 201,
        "topic_id": 203,
        "execution_id": 202,
        "owner_id": 207,
        "tournament_id": 209,
        "user_id": 210,
    },
    {
        "course_id": 211,
        "topic_id": 213,
        "execution_id": 212,
        "owner_id": 217,
        "tournament_id": 219,
        "user_id": 220,
    },
    {
        "course_id": 221,
        "topic_id": 223,
        "execution_id": 222,
        "owner_id": 227,
        "tournament_id": 229,
        "user_id": 230,
    },
    {
        "course_id": 231,
        "topic_id": 233,
        "execution_id": 232,
        "owner_id": 237,
        "tournament_id": 239,
        "user_id": 240,
    },
    {
        "course_id": 241,
        "topic_id": 243,
        "execution_id": 242,
        "owner_id": 247,
        "tournament_id": 249,
        "user_id": 250,
    },
    {
        "course_id": 251,
        "topic_id": 253,
        "execution_id": 252,
        "owner_id": 257,
        "tournament_id": 259,
        "user_id": 260,
    },
    {
        "course_id": 261,
        "topic_id": 263,
        "execution_id": 262,
        "owner_id": 267,
        "tournament_id": 269,
        "user_id": 270,
    },
    {
        "course_id": 271,
        "topic_id": 273,
        "execution_id": 272,
        "owner_id": 277,
        "tournament_id": 279,
        "user_id": 280,
    },
    {
        "course_id": 281,
        "topic_id": 283,
        "execution_id": 282,
        "owner_id": 287,
        "tournament_id": 289,
        "user_id": 290,
    },
    {
        "course_id": 291,
        "topic_id": 293,
        "execution_id": 292,
        "owner_id": 297,
        "tournament_id": 299,
        "user_id": 300,
    },
    {
        "course_id": 301,
        "topic_id": 303,
        "execution_id": 302,
        "owner_id": 307,
        "tournament_id": 309,
        "user_id": 310,
    },
    {
        "course_id": 311,
        "topic_id": 313,
        "execution_id": 312,
        "owner_id": 317,
        "tournament_id": 319,
        "user_id": 320,
    },
    {
        "course_id": 321,
        "topic_id": 323,
        "execution_id": 322,
        "owner_id": 327,
        "tournament_id": 329,
        "user_id": 330,
    },
    {
        "course_id": 331,
        "topic_id": 333,
        "execution_id": 332,
        "owner_id": 337,
        "tournament_id": 339,
        "user_id": 340,
    },
    {
        "course_id": 341,
        "topic_id": 343,
        "execution_id": 342,
        "owner_id": 347,
        "tournament_id": 349,
        "user_id": 350,
    },
    {
        "course_id": 351,
        "topic_id": 353,
        "execution_id": 352,
        "owner_id": 357,
        "tournament_id": 359,
        "user_id": 360,
    },
    {
        "course_id": 361,
        "topic_id": 363,
        "execution_id": 362,
        "owner_id": 367,
        "tournament_id": 369,
        "user_id": 370,
    },
    {
        "course_id": 371,
        "topic_id": 373,
        "execution_id": 372,
        "owner_id": 377,
        "tournament_id": 379,
        "user_id": 380,
    },
    {
        "course_id": 381,
        "topic_id": 383,
        "execution_id": 382,
        "owner_id": 387,
        "tournament_id": 389,
        "user_id": 390,
    },
    {
        "course_id": 391,
        "topic_id": 393,
        "execution_id": 392,
        "owner_id": 397,
        "tournament_id": 399,
        "user_id": 400,
    },
    {
        "course_id": 401,
        "topic_id": 403,
        "execution_id": 402,
        "owner_id": 407,
        "tournament_id": 409,
        "user_id": 410,
    },
    {
        "course_id": 411,
        "topic_id": 413,
        "execution_id": 412,
        "owner_id": 417,
        "tournament_id": 419,
        "user_id": 420,
    },
    {
        "course_id": 421,
        "topic_id": 423,
        "execution_id": 422,
        "owner_id": 427,
        "tournament_id": 429,
        "user_id": 430,
    },
    {
        "course_id": 431,
        "topic_id": 433,
        "execution_id": 432,
        "owner_id": 437,
        "tournament_id": 439,
        "user_id": 440,
    },
    {
        "course_id": 441,
        "topic_id": 443,
        "execution_id": 442,
        "owner_id": 447,
        "tournament_id": 449,
        "user_id": 450,
    },
    {
        "course_id": 451,
        "topic_id": 453,
        "execution_id": 452,
        "owner_id": 457,
        "tournament_id": 459,
        "user_id": 460,
    },
    {
        "course_id": 461,
        "topic_id": 463,
        "execution_id": 462,
        "owner_id": 467,
        "tournament_id": 469,
        "user_id": 470,
    },
    {
        "course_id": 471,
        "topic_id": 473,
        "execution_id": 472,
        "owner_id": 477,
        "tournament_id": 479,
        "user_id": 480,
    },
    {
        "course_id": 481,
        "topic_id": 483,
        "execution_id": 482,
        "owner_id": 487,
        "tournament_id": 489,
        "user_id": 490,
    },
    {
        "course_id": 491,
        "topic_id": 493,
        "execution_id": 492,
        "owner_id": 497,
        "tournament_id": 499,
        "user_id": 500,
    },
]
