spring:
  main:
    web-application-type: none    # no web server needed
  autoconfigure:
    exclude:
      - org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration
      - org.springframework.boot.autoconfigure.orm.jpa.HibernateJpaAutoConfiguration
      - org.springframework.boot.autoconfigure.groovy.template.GroovyTemplateAutoConfiguration

eureka:
  client:
    enabled: false                # no service discovery needed for local analysis

simulator:
  analysis:
    target-applications-dir: /applcations
    target-application-base-package: pt.ulisboa.tecnico.socialsoftware.quizzes
