import { type Module, inject } from "langium";
import {
  createDefaultModule,
  createDefaultSharedModule,
  type DefaultSharedModuleContext,
  type LangiumServices,
  type LangiumSharedServices,
  type PartialLangiumServices,
} from "langium/lsp";
import {
  NebulaGeneratedModule,
  NebulaGeneratedSharedModule,
} from "./generated/module.js";
import {
  NebulaValidator,
  registerValidationChecks,
} from "./nebula-validator.js";
import { NebulaScopeComputation } from './nebula-scope-computation.js';
import { NebulaScopeProvider } from '../cli/core/nebula-scope-provider.js';

/**
 * Declaration of custom services - add your own service classes here.
 */
export type NebulaAddedServices = {
  validation: {
    NebulaValidator: NebulaValidator;
  };
};

/**
 * Union of Langium default services and your custom services - use this as constructor parameter
 * of custom service classes.
 */
export type NebulaServices = LangiumServices & NebulaAddedServices;

/**
 * Dependency injection module that overrides Langium default services and contributes the
 * declared custom services. The Langium defaults can be partially specified to override only
 * selected services, while the custom services must be fully specified.
 */
export const NebulaModule: Module<
  NebulaServices,
  PartialLangiumServices & NebulaAddedServices
> = {
  validation: {
    NebulaValidator: () => new NebulaValidator(),
  },
  references: {
    ScopeComputation: (services) => new NebulaScopeComputation(services),
    ScopeProvider: (services) => new NebulaScopeProvider(services),
  },
};

/**
 * Create the full set of services required by Langium.
 *
 * First inject the shared services by merging two modules:
 *  - Langium default shared services
 *  - Services generated by langium-cli
 *
 * Then inject the language-specific services by merging three modules:
 *  - Langium default language-specific services
 *  - Services generated by langium-cli
 *  - Services specified in this file
 *
 * @param context Optional module context with the LSP connection
 * @returns An object wrapping the shared services and the language-specific services
 */
export function createNebulaServices(context: DefaultSharedModuleContext): {
  shared: LangiumSharedServices;
  nebulaServices: NebulaServices;
} {
  const shared = inject(
    createDefaultSharedModule(context),
    NebulaGeneratedSharedModule
  );
  const Nebula = inject(
    createDefaultModule({ shared }),
    NebulaGeneratedModule,
    NebulaModule
  );
  shared.ServiceRegistry.register(Nebula);
  registerValidationChecks(Nebula);

  return { shared, nebulaServices: Nebula };
}
