# Profile Configuration
spring.profiles.active=@activatedProperties@

# Maven Properties
maven.basedir=@project.basedir@

# Application Configuration
spring.application.name=answers
server.port=9115

# Database Configuration
spring.datasource.url=jdbc:postgresql://postgres:5432/answers_db
spring.datasource.driver-class-name=org.postgresql.Driver
spring.datasource.username=postgres
spring.datasource.password=password

# JPA Configuration
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=create-drop
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.jakarta.persistence.sharedCache.mode=UNSPECIFIED

# Scheduling Configuration
spring.task.scheduling.pool.size=5

# Retry Configuration
retry.db.maxAttempts=3
retry.db.delay=200
retry.db.multiplier=2

# Template Configuration
spring.groovy.template.check-template-location=false
