environment:
  microservices_num: 8
  nodes_num: 3
  reward_type: "global_average_latency"
  observation_type: "complex"
  alpha: 0.5
  beta: 0.5

workloads:
  workloads: ["user_wl.py"]
  # Interval of min, max users per workload
  users: [50, 50]
  # Interval for dynamic read/write workload multipliers
  weights_ratio: [1, 1]
  # Interval for wait time in seconds between requests
  wait_time: [0.1, 0.1]
  # Each workload (step) runs for this exact time regardless of the requests processed
  run-time: 0 # seconds
  # Each workload (step) executes this amount of tasks
  iterations: [100, 100]
  # NOTE: If you want to use iterations instead of run-time, simply set 'run-time: 0'

ppo_hyperparameters:
  learning_rate: 0.0003
  gamma: 0.99
  ent_coef: 0.01
  n_steps: 16 # 6 * 16 = 96
  batch_size: 32 # Batch size 32 means 3 mini-batches.
  n_epochs: 10
  clip_range: 0.2

training:
  num_envs: 6
  steps_per_episode: 15
  total_timesteps: 3000
  checkpoint_freq: 96

paths:
  models_dir: "./models/"
  checkpoints_dir: "./models/checkpoints/"
  tensorboard_log: "./tensorboard_logs/"
