environment:
  microservices_num: 8
  nodes_num: 3
  reward_type: "global_average_latency"
  observation_type: "complex"
  alpha: 0.5
  beta: 0.5

workloads:
  workloads:
    [
      "base_wl.py",
      "semester_start_wl.py",
      "tournament_period_wl.py",
      "steady_wl.py",
    ]
  # Interval of min, max users per workload
  users: [100, 300]
  # Interval for dynamic read/write workload multipliers
  weights_ratio: [0.5, 2.0]
  # Interval for wait time in seconds between requests
  wait_time: [0.1, 0.5]
  # Each workload (step) runs for this exact time regardless of the requests processed
  run-time: 0 # seconds
  # Each workload (step) executes this amount of tasks
  iterations: [500, 1000]
  # NOTE: If you want to use iterations instead of run-time, simply set 'run-time: 0'

ppo_hyperparameters:
  learning_rate: 0.0003
  gamma: 0.99
  ent_coef: 0.01
  n_steps: 2048
  batch_size: 64
  n_epochs: 10
  clip_range: 0.2

training:
  num_envs: 1
  steps_per_episode: 50
  total_timesteps: 100000
  eval_freq: 2048
  checkpoint_freq: 2048

paths:
  models_dir: "./models/"
  checkpoints_dir: "./models/checkpoints/"
  tensorboard_log: "./tensorboard_logs/"
