spring:
  application:
    name: course
  datasource:
    url: jdbc:postgresql://localhost:5432/${spring.application.name}db

  cloud:
    function:
      definition: commandResponseChannel;courseServiceCommandChannel;courseEventSubscriber;
    stream:
      bindings:
        course-command-channel:
          destination: ${spring.application.name}-command-channel
        courseServiceCommandChannel-in-0:
          destination: ${spring.application.name}-command-channel
          group: ${spring.application.name}-service-group
        commandResponseChannel-in-0:
          destination: ${spring.application.name}-command-responses
          group: ${spring.application.name}-response-group
        courseEventSubscriber-in-0:
          destination: event-channel
          group: ${spring.application.name}-service-group

server:
  port: 8190
grpc:
  server:
    port: 9190

routes:
  - id: ${spring.application.name}-service
    uri: lb://${spring.application.name}${gateway.service-suffix}
    predicates:
      - Path=/courses/**
    order: 1
