spring:
  application:
    name: question
  datasource:
    url: jdbc:postgresql://localhost:5432/${spring.application.name}db

  cloud:
    function:
      definition: commandResponseChannel;questionServiceCommandChannel;questionEventSubscriber;
    stream:
      bindings:
        question-command-channel:
          destination: ${spring.application.name}-command-channel
        questionServiceCommandChannel-in-0:
          destination: ${spring.application.name}-command-channel
          group: ${spring.application.name}-service-group
        commandResponseChannel-in-0:
          destination: ${spring.application.name}-command-responses
          group: ${spring.application.name}-response-group
        questionEventSubscriber-in-0:
          destination: event-channel
          group: ${spring.application.name}-service-group

server:
  port: 8194
grpc:
  server:
    port: 9194

routes:
  - id: ${spring.application.name}-service
    uri: lb://${spring.application.name}${gateway.service-suffix}
    predicates:
      - Path=/questions/**, /courses/*/questions/**
    order: 5
