package pt.ulisboa.tecnico.socialsoftware.ms.sagas.aggregate;

public enum SagaState {
    // generic states
    NOT_IN_SAGA,
    IN_SAGA,

    // tournament functionalities
    CREATE_TOURNAMENT_READ_CREATOR,
    CREATE_TOURNAMENT_READ_COURSE,
    CREATE_TOURNAMENT_READ_TOPIC,
    
    UPDATE_TOURNAMENT_READ_TOURNAMENT,
    UPDATE_TOURNAMENT_READ_TOPIC,
    UPDATE_TOURNAMENT_READ_UPDATED_TOPICS,
    UPDATE_TOURNAMENT_READ_QUIZ,

    LEAVE_TOURNAMENT_READ_TOURANMENT,

    SOLVE_QUIZ_READ_TOURNAMENT,
    SOLVE_QUIZ_STARTED_TOURNAMENT_QUIZ,
    SOLVE_QUIZ_STARTED_QUIZ,

    CANCEL_TOURNAMENT_READ_TOURNAMENT,

    REMOVE_TOURNAMENT_READ_TOURNAMENT,
}