package pt.ulisboa.tecnico.socialsoftware.ms.sagas.aggregate;

public enum SagaState {
    // generic states
    NOT_IN_SAGA,
    IN_SAGA,

    // tournament functionalities
    CREATE_TOURNAMENT_READ_CREATOR,
    CREATE_TOURNAMENT_READ_COURSE,
    CREATE_TOURNAMENT_READ_TOPIC,

    ADD_PARTICIPANT_READ_TOURNAMENT,
    ADD_PARTICIPANT_READ_USER,
    
    UPDATE_TOURNAMENT_READ_TOURNAMENT,
    UPDATE_TOURNAMENT_READ_TOPIC,
    UPDATE_TOURNAMENT_READ_UPDATED_TOPICS,
    UPDATE_TOURNAMENT_READ_QUIZ,

    LEAVE_TOURNAMENT_READ_TOURANMENT,

    SOLVE_QUIZ_READ_TOURNAMENT,
    SOLVE_QUIZ_STARTED_TOURNAMENT_QUIZ,
    SOLVE_QUIZ_STARTED_QUIZ,

    CANCEL_TOURNAMENT_READ_TOURNAMENT,

    REMOVE_TOURNAMENT_READ_TOURNAMENT,

    // course execution functionalities
    REMOVE_COURSE_EXECUTION_READ_COURSE,

    ADD_STUDENT_READ_COURSE,

    REMOVE_STUDENT_FROM_COURSE_EXECUTION_READ_COURSE,
    
    ANONYMIZE_STUDENT_READ_COURSE,

    UPDATE_STUDENT_NAME_READ_STUDENT,
    UPDATE_STUDENT_NAME_READ_COURSE,

    // question functionalities
    UPDATE_QUESTION_READ_QUESTION,

    REMOVE_QUESTION_READ_QUESTION,

    UPDATE_QUESTION_TOPICS_READ_QUESTION,

    // quiz answer functionalities
    ANSWER_QUESTION_READ_QUESTION,
    ANSWER_QUESTION_READ_QUIZ_ANSWER,

    START_QUIZ_READ_QUIZ,

    CONCLUDE_QUIZ_READ_QUIZ_ANSWER,

    // topic functionalities
    UPDATE_TOPIC_READ_TOPIC,

    DELETE_TOPIC_READ_TOPIC,

    // user functionalities
    ACTIVATE_USER_READ_USER,

    DELETE_USER_READ_USER,
}