services:
  loki:
    image: grafana/loki:3.0.0
    ports:
      - "3100:3100"
    command: -config.file=/etc/loki/local-config.yaml
    volumes:
      - ./loki/config:/etc/loki
    networks:
      postgres_postgres-network:
        ipv4_address: 172.20.0.5
  grafana:
    image: grafana/grafana:10.4.4
    ports:
      - "3000:3000"
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=admin
      - GF_SECURITY_ADMIN_USER=admin
    volumes:
      - grafana-storage:/var/lib/grafana
    networks:
      postgres_postgres-network:
        ipv4_address: 172.20.0.6
  promtail:
    image: grafana/promtail:3.0.0
    volumes:
      - /var/log:/var/log
      - ./promtail/config:/etc/promtail
      - ./logs:/app/logs
    command: -config.file=/etc/promtail/local-config.yaml
    networks:
      postgres_postgres-network:
        ipv4_address: 172.20.0.7

volumes:
  grafana-storage:

networks:
  postgres_postgres-network:
    external: true