apiVersion: v1
kind: Service
metadata:
  name: execution-service
  namespace: microservices-simulator
spec:
  selector:
    app: execution-service
  ports:
    - port: 8083
      targetPort: 8083
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: execution-service
  namespace: microservices-simulator
spec:
  replicas: 1
  selector:
    matchLabels:
      app: execution-service
  template:
    metadata:
      labels:
        app: execution-service
    spec:
      serviceAccountName: microservices-sa
      containers:
        - name: execution-service
          image: simulatorcr.azurecr.io/quizzes:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 8083
          resources:
            requests:
              memory: "256Mi"
              cpu: "50m"
            limits:
              memory: "512Mi"
              cpu: "500m"
          env:
            - name: START_CLASS
              value: "pt.ulisboa.tecnico.socialsoftware.quizzes.microservices.execution.ExecutionServiceApplication"
            - name: SPRING_PROFILES_ACTIVE
              value: "kubernetes,execution-service,sagas,stream,distributed-version"
            - name: SPRING_DATASOURCE_URL
              value: "jdbc:postgresql://postgres:5432/executiondb"
            - name: SPRING_RABBITMQ_HOST
              value: "rabbitmq"
            - name: OTEL_EXPORTER_OTLP_ENDPOINT
              value: "http://jaeger:4317"
          readinessProbe:
            httpGet:
              path: /actuator/health
              port: 8083
            initialDelaySeconds: 60
            periodSeconds: 10
